hosts: [
  { host_ip: "172.21.1.31", host_name: "stg001031"},
  { host_ip: "172.21.1.32", host_name: "stg001032"},
  { host_ip: "172.21.1.33", host_name: "stg001033"},
  { host_ip: "172.21.1.34", host_name: "stg001034"},
  { host_ip: "172.21.1.41", host_name: "stg001041"},
  { host_ip: "172.21.1.42", host_name: "stg001042"},
  { host_ip: "172.21.1.46", host_name: "stg001046"},
  { host_ip: "172.21.1.47", host_name: "stg001047"},
  { host_ip: "172.21.1.48", host_name: "stg001048"},
  { host_ip: "172.21.1.49", host_name: "stg001049"},
  { host_ip: "172.21.1.61", host_name: "stg001061"},
  { host_ip: "172.21.1.62", host_name: "stg001062"},
  { host_ip: "172.21.1.63", host_name: "stg001063"},
  { host_ip: "172.21.2.131", host_name: "stg002131"},
  { host_ip: "172.21.2.132", host_name: "stg002132"},
  { host_ip: "172.21.2.133", host_name: "stg002133"},
  { host_ip: "172.21.2.134", host_name: "stg002134"},
  { host_ip: "172.21.2.135", host_name: "stg002135"},
  { host_ip: "172.21.2.136", host_name: "stg002136"} 
  ]

obsolete_services:
  - puppet
  - chef-client

centos_files: [
     # { src: "CentOS-Base.repo", dest: "/etc/yum.repos.d/CentOS-Base.repo" },
  ]

